### ISSUE TITLE
why is username/password necessary for nifi-keycloak?

### ISSUE THREAD

**Issue by andrewzah** [ChrisEnglert/nifi-addons#1]
Hi, firstly thank you for your work.

Reading the documentation for nifi-keycloak, in authorizers.xml, why is username/password needed? I tried running nifi without those set, but ran into 401 unauthorized errors. Shouldn't the keycloak discovery url, `client_id` and `client_secret` suffice?

**Comment by ChrisEnglert** [comment]
Hello, sry for the late reply!

the username and password is of a User that is allowed to access KeyCloak via KeyCloak API.
Right now I don't see a way to allow only a client (use a clientId and clientSecret) without specifying a (System-) user

The user needs to have the permission to use KeyCloak API.
I'm working on improving the documentation with a flow setting up a keycloak user for that
